### ISSUE TITLE
Color manipulation

### ISSUE THREAD

**Issue by funtoosh** [Fontself/TypeWithPride#1]
First of all: this is great!!

But I was wondering, if there is a way to manipulate the colors of the letters?
Could you add an SVG version of the font, which might allow for easy color manipulation in the source code?

Cheers,
-f

**Comment by franzh** [comment]
Thanks @funtoosh So Photoshop does currently not give you access to the specific colors of the OpenType-SVG fonts, which could potentially be exposed via a custom color palette (see CPAL on https://www.microsoft.com/typography/otspec/svg.htm). This is hopefully something we can ship in a future release of the font.

FYI, we'll soon provide a first set of shape files so you could create any derivate work, including SVG ones. Stay tuned ;)

**Comment by funtoosh** [comment]
I will! Merci bien …

**Comment by funtoosh** [comment]
Hi @franzh, any news yet on the shapes and SVGs, or the source files? 
;~}

**Comment by franzh** [comment]
Yes @funtoosh you can get some of the shapes from [an EPS file on the repo](https://github.com/Fontself/TypeWithPride/blob/master/artwork/art-sources/TypeWithPride_Gilbert_design-flat.eps) and FYI there is now an animated version of Gilbert too: https://animography.net/products/gilbert

These are just first steps, more will come later on - still busy releasing the [Type With Pride Contest](https://www.typewithpride.com/contest) winning entries and preparing cool new updates ;)

**Comment by funtoosh** [comment]
Hey, yeah, that EPS helps a lot! 
Love all the work that keeps going into that project,
Groetjes, -F
